dependencies {
  implementation fileTree(dir: 'libs', include: '*.jar')
  implementation project(":core")
 // implementation project(":mail")
  implementation project(":pg")
  implementation project(":util")
  implementation project(":pkix")
  implementation project(":prov")
  implementation project(":tls")
  testImplementation group: 'junit', name: 'junit', version: '4.11'
}

// Task để chạy CustomCurveExample
task runExample(type: JavaExec) {
    group = 'application'
    description = 'Runs the CustomCurveExample'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'org.bouncycastle.examples.CustomCurveExample'
    standardInput = System.in
}

